CREATE TABLE IF NOT EXISTS companies (
Id INT AUTO_INCREMENT PRIMARY KEY,
Ticker VARCHAR(10) NOT NULL UNIQUE,
Name VARCHAR(120) NOT NULL
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS stock_quotes (
Id BIGINT AUTO_INCREMENT PRIMARY KEY,
CompanyId INT NOT NULL,
QuoteDate DATE NOT NULL,
Open DECIMAL(10,2) NOT NULL,
High DECIMAL(10,2) NOT NULL,
Low DECIMAL(10,2) NOT NULL,
Close DECIMAL(10,2) NOT NULL,
Volume BIGINT NOT NULL,
CONSTRAINT fk_company FOREIGN KEY (CompanyId) REFERENCES companies(Id),
UNIQUE KEY uq_company_date (CompanyId, QuoteDate)
) ENGINE=InnoDB;